- id: clean-requirements
  name: Clean requirements
  description: Remove unused or wrong entries from requirements.txt
  entry: clean-requirements
  language: python
  files: requirements.*\.txt$
  types: [text]
- id: no-telegram-tokens
  name: No Telegram tokens
  description: Detect whether potential Telegram bot tokens are committed by mistake
  entry: no-telegram-tokens
  language: python
  types: [text]
